on:
  push:
    branches:
      - master
name: Publish stories

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and deploy storybook
      uses: JamesIves/github-pages-deploy-action@v4
      env:
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        BRANCH: storybook-static
        FOLDER: storybook-static
        BUILD_SCRIPT: npm install && npm run build-storybook
