name: Build and Deploy
on: 
  push:
    - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Build
        run: | 
          npm install
          npm run build-storybook
      - name: Deploy Storybook
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          BRANCH: main
          FOLDER: docs-build
          CLEAN: true
          TARGET_FOLDER: docs
